### ISSUE TITLE
Windows node with ContainerD can't run flannel and kubeproxy daemonsets

### ISSUE THREAD

**Issue by vitaliy-leschenko** [kubernetes-sigs/sig-windows-tools#128]
**Describe the bug**
Flannel and kube-proxy pods do not start.

**To Reproduce**
1. setup on-premise cluster (v1.19.0) with flannel (vxlan)
 - flannel image: vleschenko/flannel:0.13.0 (it is support WS2004)
 - kubeproxy image: vleschenko/kube-proxy:v1.19.0
2. setup Windows Server Standard 2004
3. [install containerd](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/scripts/Install-Containerd.ps1)
4. [prepare node](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/scripts/PrepareNode.ps1)
5. kubeadm join

Node successfully joined to cluster:
```
PS C:\Users\v.leschenko> kubectl get nodes -owide
NAME           STATUS   ROLES    AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                  KERNEL-VERSION       CONTAINER-RUNTIME
k8s            Ready    master   241d   v1.19.0   192.168.2.20   <none>        Ubuntu 18.04.5 LTS        4.15.0-123-generic   docker://19.3.12
k8s-us1804-a   Ready    <none>   241d   v1.19.0   192.168.2.25   <none>        Ubuntu 18.04.5 LTS        4.15.0-123-generic   docker://19.3.12
k8s-ws2004-a   Ready    <none>   47m    v1.19.0   192.168.2.30   <none>        Windows Server Standard   10.0.19041.630       containerd://1.4.1
```

Pods stuck on ContainerCreating
```
kube-flannel-ds-windows-amd64-zclk9   0/1     ContainerCreating   0          18m     192.168.2.30   k8s-ws2004-a   <none>           <none>
kube-proxy-windows-gqjnh              0/1     ContainerCreating   0          18m     <none>         k8s-ws2004-a   <none>           <none>
```

Error message:
```
  Warning  FailedCreatePodSandBox  4m22s (x63 over 17m)  kubelet, k8s-ws2004-a  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "fe980b773114549b7144eaa3bbd44f277394ad7be669697a442141372da3f29c": error creating endpoint hcnCreateEndpoint failed in Win32: IP address is either invalid or not part of any configured subnet(s). (0x803b001e) {"Success":false,"Error":"IP address is either invalid or not part of any configured subnet(s). ","ErrorCode":2151350302} : endpoint config &{ fe980b773114549b7144eaa3bbd44f277394ad7be669697a442141372da3f29c_nat 8f77950d-c85e-4b74-b9dc-61ce5e671d3a  [] [{ 0}] { [.] [127.0.0.1] []} [{192.168.2.30 0.0.0.0/0 0}]  0 {2 0}}
```

**Expected behavior**
flannel and kube-proxy started

**Kubernetes (please complete the following information):**
 - Windows Server version: Windows Server 2004
 - Kubernetes Version: 1.19.0
 - CNI: ContainerD/1.4.1

**Comment by vitaliy-leschenko** [comment]
@marosset could you help with it?

**Comment by vitaliy-leschenko** [comment]
After VM reboot in kubelet logs I can see:
```
E1127 10:50:46.560757    3224 remote_runtime.go:113] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to setup network for sandbox "976a7614895c88721d7e5e45d598643dc90f4bd3fc9ad8fb6184374f2b4dfde1": hcnCreateNetwork failed in Win32: The object already exists. (0x1392) {"Success":false,"Error":"The object already exists. ","ErrorCode":2147947410}
E1127 10:50:46.560757    3224 kuberuntime_sandbox.go:69] CreatePodSandbox for pod "kube-flannel-ds-windows-amd64-zclk9_kube-system(d168e243-716c-47b4-8ae5-a5d01399ac1c)" failed: rpc error: code = Unknown desc = failed to setup network for sandbox "976a7614895c88721d7e5e45d598643dc90f4bd3fc9ad8fb6184374f2b4dfde1": hcnCreateNetwork failed in Win32: The object already exists. (0x1392) {"Success":false,"Error":"The object already exists. ","ErrorCode":2147947410}
E1127 10:50:46.560757    3224 kuberuntime_manager.go:730] createPodSandbox for pod "kube-flannel-ds-windows-amd64-zclk9_kube-system(d168e243-716c-47b4-8ae5-a5d01399ac1c)" failed: rpc error: code = Unknown desc = failed to setup network for sandbox "976a7614895c88721d7e5e45d598643dc90f4bd3fc9ad8fb6184374f2b4dfde1": hcnCreateNetwork failed in Win32: The object already exists. (0x1392) {"Success":false,"Error":"The object already exists. ","ErrorCode":2147947410}
E1127 10:50:46.560757    3224 pod_workers.go:191] Error syncing pod d168e243-716c-47b4-8ae5-a5d01399ac1c ("kube-flannel-ds-windows-amd64-zclk9_kube-system(d168e243-716c-47b4-8ae5-a5d01399ac1c)"), skipping: failed to "CreatePodSandbox" for "kube-flannel-ds-windows-amd64-zclk9_kube-system(d168e243-716c-47b4-8ae5-a5d01399ac1c)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-flannel-ds-windows-amd64-zclk9_kube-system(d168e243-716c-47b4-8ae5-a5d01399ac1c)\" failed: rpc error: code = Unknown desc = failed to setup network for sandbox \"976a7614895c88721d7e5e45d598643dc90f4bd3fc9ad8fb6184374f2b4dfde1\": hcnCreateNetwork failed in Win32: The object already exists. (0x1392) {\"Success\":false,\"Error\":\"The object already exists. \",\"ErrorCode\":2147947410}"
```
ipconfig:
```
Windows IP Configuration


Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : vitaliy.org
   IPv6 Address. . . . . . . . . . . : 2a03:e2c0:1801:ff00:2551:7e41:8ae0:4fc6
   IPv6 Address. . . . . . . . . . . : 2a03:e2c0:1801:ff00:8c2c:2f9:601a:d106
   Link-local IPv6 Address . . . . . : fe80::8c2c:2f9:601a:d106%7
   IPv4 Address. . . . . . . . . . . : 192.168.2.30
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : fe80::215:5dff:fe02:903%7
                                       192.168.2.254
```

**Comment by marosset** [comment]
I'll take a look

**Comment by vitaliy-leschenko** [comment]
@marosset I found reason why pod doesn't start: After node restart `nat` network has been removed.
So, I modified StartKubelet.ps1 to recreate it like for docker. Please see this script from PR #132 

Now pod starts but use wrong network: nat instead of flannel

**Comment by marosset** [comment]
@vitaliy-leschenko I wonder if there is a race between when kube-proxy and flannel-ds pod is able to start the flannel service.
On docker machines I observed that flannel would remove NoSchedule taints on machines to allow for other pods like kube-proxy to be scheduled.
I don't remember seeing seeing this behavior on nodes running contianerd.

Most of my experience with containerd is with setting up CNI during node configuration time, not with having CNI plugins being deployed with via pods.

@daschott do you have any insight here?

**Comment by vitaliy-leschenko** [comment]
flannel pod has the same behaviour for docker and cotnainerd nodes.

**Comment by marosset** [comment]
If kube-proxy pod is rescheduled after flannel is started does it join the correct (flannel) network?
I'm setting up a new cluster to verify this myself.

I think I remember docker nodes getting joined to the cluster in a NotReady state then the flannel service would update the node's status setting it to Ready but cointainerd nodes would get joined in the Ready state.

**Comment by vitaliy-leschenko** [comment]
yep. even if kube-proxy (or any other pods) started after flannel it also starts with NAT ip address.

**Comment by marosset** [comment]
I'm able to repro this.
Still looking at the issue tho...

**Comment by marosset** [comment]
Sorry for the slow responses here.
I've been digging into this and have a lot more context but do not yet have a solution.

When hostNetwork is true kubelet/dockershim adds the containers to an existing network named `host` and skips CNI specific config (created by https://github.com/kubernetes-sigs/sig-windows-tools/blob/9aa36e43ef71947b263464b3e657e50340769315/kubeadm/scripts/PrepareNode.ps1#L77)

It looks like containerd for Windows does not have the same behavior
https://github.com/containerd/containerd/blob/88f089354009d3df6d5556d59ce4ce2ac0717106/pkg/cri/server/sandbox_run.go#L111-L117

I also ran some testing and locally where I configured flannel on the node before joining the node to a cluster (installed / ran flanneld and added a flannel CNI config in /etc/cni/net.d) and then did not schedule a Windows flannel ds to the node and everything worked as expected.

I think some possible solutions are to
- Not bring in CNI config/plugins via a deamonset pod (install create seperate scripts that should be run after PrepareNode.ps1)
- Update contiainerd to better support hostNetwork mode for Windows.

All of the upstream tests we run against kubernetes/kubernetes install CNI as part of node preparation (for both Azure and GKE) and unfortunately these tutorials missed this behavior.

**Comment by xmapst** [comment]
> **Describe the bug**
> Flannel and kube-proxy pods do not start.
> 
> **To Reproduce**
> 
> 1. setup on-premise cluster (v1.19.0) with flannel (vxlan)
> 
> * flannel image: vleschenko/flannel:0.13.0 (it is support WS2004)
> * kubeproxy image: vleschenko/kube-proxy:v1.19.0 (it is support WS2004)
> 
> 1. setup Windows Server Standard 2004
> 2. [install containerd](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/scripts/Install-Containerd.ps1)
> 3. [prepare node](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/scripts/PrepareNode.ps1)
> 4. kubeadm join
> 
> Node successfully joined to cluster:
> 
> ```
> PS C:\Users\v.leschenko> kubectl get nodes -owide
> NAME           STATUS   ROLES    AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                  KERNEL-VERSION       CONTAINER-RUNTIME
> k8s            Ready    master   241d   v1.19.0   192.168.2.20   <none>        Ubuntu 18.04.5 LTS        4.15.0-123-generic   docker://19.3.12
> k8s-us1804-a   Ready    <none>   241d   v1.19.0   192.168.2.25   <none>        Ubuntu 18.04.5 LTS        4.15.0-123-generic   docker://19.3.12
> k8s-ws2004-a   Ready    <none>   47m    v1.19.0   192.168.2.30   <none>        Windows Server Standard   10.0.19041.630       containerd://1.4.1
> ```
> 
> Pods stuck on ContainerCreating
> 
> ```
> kube-flannel-ds-windows-amd64-zclk9   0/1     ContainerCreating   0          18m     192.168.2.30   k8s-ws2004-a   <none>           <none>
> kube-proxy-windows-gqjnh              0/1     ContainerCreating   0          18m     <none>         k8s-ws2004-a   <none>           <none>
> ```
> 
> Error message:
> 
> ```
>   Warning  FailedCreatePodSandBox  4m22s (x63 over 17m)  kubelet, k8s-ws2004-a  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "fe980b773114549b7144eaa3bbd44f277394ad7be669697a442141372da3f29c": error creating endpoint hcnCreateEndpoint failed in Win32: IP address is either invalid or not part of any configured subnet(s). (0x803b001e) {"Success":false,"Error":"IP address is either invalid or not part of any configured subnet(s). ","ErrorCode":2151350302} : endpoint config &{ fe980b773114549b7144eaa3bbd44f277394ad7be669697a442141372da3f29c_nat 8f77950d-c85e-4b74-b9dc-61ce5e671d3a  [] [{ 0}] { [.] [127.0.0.1] []} [{192.168.2.30 0.0.0.0/0 0}]  0 {2 0}}
> ```
> 
> **Expected behavior**
> flannel and kube-proxy started
> 
> **Kubernetes:**
> 
> * Windows Server version: Windows Server 2004
> * Kubernetes Version: 1.19.0
> * CNI: ContainerD/1.4.1

Have you solved it, how did you solve it

**Comment by sl844** [comment]
Hi, I am running into a similar issue. Has there been a solution to this yet?

**Comment by jsturtevant** [comment]
The current way around this is to install your CNI of choice on the node after the prepare script, then you can run kubeproxy as a deamonset.

We are looking into [Windows privileged container support](https://github.com/kubernetes/enhancements/pull/2037) (which comes with host network support). This is a topic for the next sig-windows meeting if you want to join and discuss further: https://docs.google.com/document/d/1Tjxzjjuy4SQsFSUVXZbvqVb64hjNAG5CQX8bK7Yda9w/edit#heading=h.3f5dhus4q8i2

**Comment by sl844** [comment]
okay. Thanks I will try that route.

**Comment by jaderoliver** [comment]
@vitaliy-leschenko Hi dude, I am have this same problem now with my win server 2019, after restart the machine they report the same error with you, could you show where you change the StartKubelet.ps1, in my case I am using just the containerd wihout docker you know because k8s will not suporte docker.

**Comment by vitaliy-leschenko** [comment]
@jaderoliver Hi, I have not solved the issue yet. 
I'm going to try write scripts to setup containerd as a service instead of run it as a pods.
Maybe it will works better.

**Comment by sl844** [comment]
I wasn't able to get it to work too with a manual installation of flannel and daemonset kube-proxy. Although things deployed, I wasn't able to do cross node communication between pods.

**Comment by jsturtevant** [comment]
@sl844 did you install flannel as a service?  We have seen success with install containerd and flannel as a service: https://github.com/kubernetes-sigs/sig-windows-tools/issues/128#issuecomment-744840966 instead of running them as pods

**Comment by sl844** [comment]
I installed it with the command flanneld -- kubeconfig-file=c:\k\config --iface=server_ip --ip-masq=1 --kube-subnet-mgr=1 -v=3. 
 Orginally, I had tried to run it following the run script in the flannel yaml file, but I got errors about setting the pod_name and namespace. When I manually set that, it looks for the pod with respect to the pod_name which isn't deployed. Are there steps to installing it as a service?

**Comment by daschott** [comment]
@sl844 When running directly on node, you have to set `NODE_NAME` env var instead. For example:
```$env:NODE_NAME=$(hostname).toLower()```

**Comment by sl844** [comment]
When I set the environment variable to use node_name it works, but cross node communication between pods don't work. I tried this twice but without using nssm.

**Comment by daschott** [comment]
What do flannelD logs print out?

**Comment by sl844** [comment]
I don't recall it. I will try to set it up as a service and get the logs.

**Comment by sl844** [comment]
https://drive.google.com/drive/folders/14G4x-QvtB6fhZ7f0eAD0JwalKEZV29VO
You can find the flannel output, picture of kube-proxy with IP, Picture of pods deployed on windows and also flannel conf in the link above.

Steps: 
1. Install-Containerd.ps1
2. Prepare-Node.ps1
3. Install Flannel (1.13.0) using nssm
  - Set NODE_NAME
  - kubeconfig-file=c:\k\config --iface=Server_IP --ip-masq=1 --kube-subnet-mgr=1
4. Deploy kube-proxy daemonset
5. Deploy Sig/windows app(windows)+database(linux)

**Comment by daschott** [comment]
@sl844 It looks like the Windows app (signup-web) is attached to NAT network instead of Flannel network. Ie it is using the network that is intended for the daemonsets, not for workloads. This NAT network will not allow for such communication between hosts. Can you switch kubelet over to use the Flannel network config?

**Comment by sl844** [comment]
Is the switch the --network-plugin=cni in the StartKubelet.ps1 script? That is already set.

**Comment by daschott** [comment]
There seems to be another CNI config currently being used pointing to NAT CNI plugin. The CNI config gets pointed to in different places:
ContainerD will point to a CNI config in its `config.toml`
Kubelet has a parameter `cni-conf-dir`

If there are multiple CNI configuration files in the directory, the kubelet uses the configuration file that comes first by name in lexicographic order. The default path to this directory is `c:/etc/cni/net.d`.

You likely have another NAT CNI configuration file that is still present from some of the setup used for the DaemonSet workaround which is taking higher precedence. Can you check the `c:/etc/cni/net.d` directory? 

Also keep in mind you should restart Kubelet after any CNI config changes. For full re-read after CNI config change:
```
<kubectl delete pods on problematic node>
Stop-Service Kubelet
Restart-Service ContainerD
Start-Service Kubelet
<wait for node to report as ready> 
<reschedule pods>
```

**Comment by sl844** [comment]
You are right, I have two files. One is created by the Install-Container.ps1 script. The other one I followed the run script on flannel.yaml and placed it in there.  By default both containerd and kubelet uses the same directory for cni.

**Comment by vio-f** [comment]
I am having similar issues.
Added the following to `StartKubelet.ps1`
```
Import-Module "c:\k\hns.psm1"
New-HnsNetwork -Type NAT -Name nat
```
And wth `flannel` and `kube-proxy` running as daemonsets. They both join the wrong network.

An interesting thing i noticed is if I reschedule `flannel` (i.e. delete the pod), then `flannel` gets the right IP for a second and then swhiches over to the wrong one (NAT?).

I would like to try to run flannel as a service - can someone help me out with  some docs/step by step guide?

**Comment by dfateyev** [comment]
I have faced the same issue as in the previous message: `flannel` initially gets the correct IP, and then falls back to an invalid one from the NAT network. `Kube-proxy-wondows` is started, but also gets an IP from the NAT network. Client PODs can be scheduled, but all of them obtain IPs from NAT.
Tried to separate network configurations for `kubelet` and `containerd`, but without success. With removing `0-containerd-nat.json`, PODs can obtain IPs from flannel network, but DaemonSets become configured incorrectly.

Can someone get more information on how to run `flannel` standalone, switching from DaemonSet?

**Comment by vitaliy-leschenko** [comment]
Hi @dfateyev,

before DaemonSets we used this scripts to join Windows node to a cluster.
https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/KubeCluster.ps1
with configs:
https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/v1.16.0/Kubeclusterbridge.json
or 
https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/v1.16.0/Kubeclustervxlan.json

When we use this way, we have kubelet, flannel and kube-proxy as 3 windows services.
Maybe it can help you to setup containerd.
My attempts have been failed.

**Comment by lippertmarkus** [comment]
anybody got this working in the meantime?

**Comment by fredericpougnault** [comment]
Have you check the config file of containerd.

    [plugins."io.containerd.grpc.v1.cri".cni]
      bin_dir = "C:/opt/cni/bin"
      conf_dir = "C:/etc/cni/net.d"
      conf_template = ""
      max_conf_num = 0

max_conf_num is the number of configuration files loaded at startup by containerd, the default value is 1.
You must have the file 0-containerd-nat.json for containerd.
Then you need to have a config file for flannel
If you put max_conf_num at 0 you solve your problem.
The both file wiil be loaded

**Comment by lippertmarkus** [comment]
@fredericpougnault thanks for the suggestion. I just tried setting `max_conf_num = 0` but I'm still getting
```
Warning  FailedCreatePodSandBox  2m13s               kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "281e81a3d54f574140123ddce86e7a9d325658a1cefc1edab410f6ee8aedc4ba": hcnCreateNetwork failed in Win32: The object already exists. (0x1392) {"Success":false,"Error":"The object already exists. ","ErrorCode":2147947410}
```
(like the other people above)

When I then manually create the NAT network with
```
Import-Module .\hns.psm1
New-HnsNetwork -Type NAT -Name nat
```

```
Warning  FailedCreatePodSandBox  10s (x9 over 118s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "06cc180b67b3feedba562c0e578003e416173f74101a9df412e759ab1c8751f6": error creating endpoint hcnCreateEndpoint failed in Win32: IP address is either invalid or not part of any configured subnet(s). (0x803b001e) {"Success":false,"Error":"IP address is either invalid or not part of any configured subnet(s). ","ErrorCode":2151350302} : endpoint config &{ 06cc180b67b3feedba562c0e578003e416173f74101a9df412e759ab1c8751f6_nat 51de8be0-dc00-424b-878d-c78afc04d88c  [] [{ 0}] { [default.svc.cluster.local svc.cluster.local cluster.local] [10.96.0.10] [ndots:5]} [{10.1.0.101 0.0.0.0/0 0}]  0 {2 0}}
```

which sounds like it tries to use the NAT network.

**Comment by FriedrichWilken** [comment]
@knabben is the expert on Calico

**Comment by HimanshuZinzuwadia** [comment]
Sad to report that even with following all the above and trying various approaches, could not get containerd and flannel to work together.   Ended with same issue as this one. https://issueexplorer.com/issue/kubernetes-sigs/sig-windows-tools/102
Update after ruined weekend.  May be I was close to solution but can't spend anymore cycles. 
Conclusion 
containerd, microsoft.sdn provided scripts for flannel and kubernetes do not work well together in current state.

Reverting to Installing Docker Enterprise and and PrepareNode.ps1 instructions under Docker tab in below URLs. https://docker-docs.netlify.app/install/windows/docker-ee/
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/ and

**Comment by lippertmarkus** [comment]
I have published an example Vagrant setup with Hyper-V using Calico and kube-proxy HostProcess pods for Windows nodes: https://github.com/lippertmarkus/vagrant-k8s-win-hostprocess

It's using plain Ubuntu/Windows Server 2022 boxes and the setup scripts are super simple: https://github.com/lippertmarkus/vagrant-k8s-win-hostprocess/tree/main/setup-scripts

Thought that might help you with your setup and the various problems posted here

**Comment by jsturtevant** [comment]
@lippertmarkus that's great!  Have you seen the devbox work the sig has been working on? https://github.com/kubernetes-sigs/sig-windows-dev-tools

We have a task to integrate the hostprocess pods https://github.com/kubernetes-sigs/sig-windows-dev-tools/issues/123. Is that something you would be willing to help out with?  

CC: @FriedrichWilken @knabben

**Comment by khatrig** [comment]
Was someone able to make Container + (flannel and kubeproxy daemonsets) work?

**Comment by lippertmarkus** [comment]
Those two ways should work flawlessly:
https://github.com/kubernetes-sigs/sig-windows-dev-tools
https://github.com/lippertmarkus/vagrant-k8s-win-hostprocess

**Comment by jonaskello** [comment]
I've tried flannel + kubeproxy deamonsets using hostprocess containers (containerd 1.6.4) but still no luck. Tried both on Windows Server 2019 and 2022. The error is still as reported above:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8e7c5b8d5569ba1c7dcda6807a1a0d3e10d3d9c6ff4873b3c5bd3ddbb460a8d4": plugin type="nat" name="nat" failed (add): hcnCreateNetwork failed in Win32: The object already exists. (0x1392) {"Success":false,"Error":"The object already exists. ","ErrorCode":2147947410}`
```

Has anyone gotten flannel working with containerd in any configuration (non-hostprocess containers, hostprocess containers, services)?

**Comment by lippertmarkus** [comment]
@jonaskello you get a "nat network already exists error", that's different to what OP got. Try to remove the already existing one:
```
Get-HNSNetwork | Remove-HNSNetwork
```

**Comment by jonaskello** [comment]
@lippertmarkus Yes you are correct, when we switched to hostprocess it is a different error from OP. Actually we got one step further by deleting the cni config file created by Install-Containerd.ps1 like you do here:

https://github.com/lippertmarkus/vagrant-k8s-win-hostprocess/blob/main/setup-scripts/winworker.ps1#L21

Now flannel and kube-proxy starts and the workload container gives error about invalid architecture on Server 2022. Will try it on 2019 also.

**Comment by K31D** [comment]
> @lippertmarkus Yes you are correct, when we switched to hostprocess it is a different error from OP. Actually we got one step further by deleting the cni config file created by Install-Containerd.ps1 like you do here:
> 
> https://github.com/lippertmarkus/vagrant-k8s-win-hostprocess/blob/main/setup-scripts/winworker.ps1#L21
> 
> Now flannel and kube-proxy starts and the workload container gives error about invalid architecture on Server 2022. Will try it on 2019 also.

Hi Jonas where you able to make it work, I am facing the same issue with ContainerD and Flannel on Windows Node

**Comment by jonaskello** [comment]
@K31D Yes we have it working now. 

Although it is not possible to run 2019 images on Server 2022 worker nodes but I found out this is a limitation of windows itself.

**Comment by K31D** [comment]
@jonaskello  may I ask you how or what was the problem ? 
Cause I am trying with WS2019+ContainerD 1.5.9 and Flannel (vxlan)

**Comment by jonaskello** [comment]
@K31D If I recall correctly deleting the CNI config as per my [comment above](https://github.com/kubernetes-sigs/sig-windows-tools/issues/128#issuecomment-1135605935) solved it for us.

**Comment by jsturtevant** [comment]
@K31D if you are using the hostprocess containers you need to use containerd 1.6+

**Comment by K31D** [comment]
Thank you @jsturtevant, no they are "regular" containers. Unfortunately, pods are keeping getting the Nat network instead of the Pod Cidr

**Comment by jsturtevant** [comment]
yea the scripts for containerd had a bug that wasn't fixable with this solution.  The only way to get flannel working with containerd is to run flanneld as a windows service on the host and only configure the flannel network not the nat config that the scripts set up.



> we are forced to use Vxlan cause we are on Azure IaaS VM.

There is no reason to only use vxlan here.  in AKS and capz the vms created as Nodes are IaaS VMs.  We have gotten all of the various cni's working including ones that use l2bridge configurations.

**Comment by jsturtevant** [comment]
we know this type of installation guide is missing, it has been challenging to create one due to differences in setups/networks and lack of parity for things like privileged containers.  We have discussed as a sig-windows to potentially fill this gap with some tutorials but have limited folks to dedicate to it.  

That basics in those scripts you link are essentially still the same as they were 3 years ago unless you are trying to use cni's and kubeproxy as hostprocess containers.   Calico also has some good docs and scripts that mostly just work: https://projectcalico.docs.tigera.io/getting-started/windows-calico/quickstart

**Comment by jonaskello** [comment]
For anyone interested I made a [gist with the scripts](https://gist.github.com/jonaskello/138d0b00aec844b045ab8f413fcd3a6e) that we have working to install windows worker nodes. We use this on freshly installed WS2019 Core machines. It uses ContainerD and flannel with host process containers.

**Comment by K31D** [comment]
Thank you again both! You have been very helpful, will try the @jonaskello script

**Comment by jsturtevant** [comment]
@jonaskello @lippertmarkus We have a need for improving our getting started for windows: https://github.com/kubernetes-sigs/sig-windows-tools/issues/217  

Would either of you be interested in helping improve our getting started story with the work you've already done?

**Comment by lippertmarkus** [comment]
@brasmith-ms also created https://github.com/microsoft/Windows-Containers/tree/Main/helpful_tools

I think it would be better to decide on one installation method we want to provide as "official" and then add all features and configuration options to that. I created the containerd-installer because we wanted [an easy way to install containerd](https://github.com/microsoft/Windows-Containers/issues/186#issuecomment-989896985) and PowerShell scripts can't be used for a WinGet target. So if we want to move forward with that, we could transfer the repo to sig-windows-tools and I'm happy to create a WinGet package for it.

Installation could look like
```
winget install containerd --override "--include-cni"
```

**Comment by ghbeta** [comment]
@K31D do you manage to make the cluster work? with script from @jonaskello i get an error from kube-proxy-windows pod due to missing cni configuration, the crictl info also report missing configuration. maybe i am missing something here

**Comment by Krishnankk** [comment]
@K31D @ghbeta 
Hi,
I have followed the script of @jonaskello and my windows worker node successfully connected to the linux master (CentOS7). pods are successfully running in the cluster. but i am not able to access via NodePort service. connection is refusing. 

Any idea ?

**Comment by DanSibbernsen** [comment]
For anyone having a similar issue while running containerd and using `host-gw` flannel, I found that restarting the box will cause the `containerd` network to drop out of scope. This can be remedied with these 2 steps:

1. `New-HnsNetwork -Type NAT -Name nat `  - create the missing network, as NAT is somehow deleted during reboot
2. `Get-HnsEndpoint | ? { $_.Name -eq 'cbr0_ep' } | Remove-HnsEndpoint`  - remove an endpoint that I *think* was still tied to the old NAT.
Step 2 I got from [#94](https://github.com/kubernetes-sigs/sig-windows-tools/issues/94#issuecomment-640176562) after getting the error message `rpc error: code = Internal desc = could not create IP forward entry: The object already exists.`
